### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by acoffman87** [fastenhealth/docs#50]
Hello,

First of all I just want to say that this i an awesome project and I am really appreciating that someone has thought to do this, finally. 

The question I want to bring up is persistent storage, I did see and tested out this in docker, and slowly in K3s as well, but one thing I am not seeing in the documentation is where the persistent storage volumes are located at.

Thank you again and I look forward to seeing the future development of this project!

**Comment by AnalogJ** [comment]
Hey @acoffman87 
Thanks for your interest!

At the moment, Fasten is still under heavy development, and I expect the database schema to change significantly -- which I why I haven't provided instructions for how to persist the database. 

If understand that you may need to wipe your DB manually between updates, you can persist the following folder: [`/opt/fasten/db/`](https://github.com/fastenhealth/fasten-onprem/blob/main/backend/pkg/config/config.go#LL31C37-L31C52) within the container using a bind/volume mount. 

Once Fasten is a bit further along in its development, I plan on adding a db migration utility, and a default bind mount to the instructions. 

Hope that answers your questions! I'll close this issue for now, but feel free to comment/reopen if you have questions.

**Comment by acoffman87** [comment]
Thank you that does answer my question. Again this is awesome thank you for all your hard work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
