### ISSUE TITLE
Add sources not working? 

### ISSUE THREAD

**Issue by chansters** [fastenhealth/docs#51]
I just installed Fasten (onprem main) using Docker but I cannot add sources?   When I click on any of the healthcare providers, nothing happens.

**Comment by chansters** [comment]
Please ignore.  It's the same issue as this: https://github.com/fastenhealth/fasten-onprem/issues/14

**Comment by AnalogJ** [comment]
hey @chansters yeah this is a known issue. I'm going to close this and follow up on our convo there.
